"""add distance_source to journeys

Revision ID: 188d8c9bd89a
Revises: cd12e28b1b89
Create Date: 2026-07-27 13:40:30.445244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188d8c9bd89a'
down_revision: Union[str, None] = 'cd12e28b1b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_journeys', sa.Column('distance_source', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_journeys', 'distance_source')
    # ### end Alembic commands ###
