"""m2_9_sessions_and_courier_auth

Revision ID: 74b54f6dc74e
Revises: d1e2f3a4b5c6
Create Date: 2026-07-27 13:19:12.645756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b54f6dc74e'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burn_sessions',
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_uuid', sa.String(length=36), nullable=True),
    sa.Column('binding_source', sa.String(length=32), nullable=True),
    sa.Column('bound_by', sa.String(length=255), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_uuid')
    )
    op.create_index(op.f('ix_burn_sessions_batch_uuid'), 'burn_sessions', ['batch_uuid'], unique=False)
    op.drop_index('ix_stage_events_batch_uuid', table_name='batch_stage_events')
    op.create_index(op.f('ix_batch_stage_events_batch_uuid'), 'batch_stage_events', ['batch_uuid'], unique=False)
    op.create_foreign_key(None, 'batches', 'source_parcels', ['parcel_uuid'], ['parcel_uuid'])
    op.drop_constraint('credit_issuances_issuance_uuid_key', 'credit_issuances', type_='unique')
    op.drop_index('ix_credit_issuances_issuance_uuid', table_name='credit_issuances')
    op.create_index(op.f('ix_credit_issuances_issuance_uuid'), 'credit_issuances', ['issuance_uuid'], unique=True)
    op.drop_constraint('uq_portal_sessions_token_hash', 'portal_sessions', type_='unique')
    op.drop_index('ix_portal_sessions_token_hash', table_name='portal_sessions')
    op.create_index(op.f('ix_portal_sessions_token_hash'), 'portal_sessions', ['token_hash'], unique=True)
    op.drop_constraint('uq_portal_users_email', 'portal_users', type_='unique')
    op.drop_index('ix_portal_users_email', table_name='portal_users')
    op.create_index(op.f('ix_portal_users_email'), 'portal_users', ['email'], unique=True)
    op.add_column('telemetry_chunks', sa.Column('session_uuid', sa.String(length=36), nullable=True))
    op.add_column('telemetry_chunks', sa.Column('courier_device_id', sa.String(length=255), nullable=True))
    op.add_column('telemetry_chunks', sa.Column('seq', sa.Integer(), nullable=True))
    op.add_column('telemetry_chunks', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    op.alter_column('telemetry_chunks', 'batch_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_telemetry_chunks_session_uuid'), 'telemetry_chunks', ['session_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_chunks_session_uuid'), table_name='telemetry_chunks')
    op.alter_column('telemetry_chunks', 'batch_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('telemetry_chunks', 'prev_hash')
    op.drop_column('telemetry_chunks', 'seq')
    op.drop_column('telemetry_chunks', 'courier_device_id')
    op.drop_column('telemetry_chunks', 'session_uuid')
    op.drop_index(op.f('ix_portal_users_email'), table_name='portal_users')
    op.create_index('ix_portal_users_email', 'portal_users', ['email'], unique=False)
    op.create_unique_constraint('uq_portal_users_email', 'portal_users', ['email'])
    op.drop_index(op.f('ix_portal_sessions_token_hash'), table_name='portal_sessions')
    op.create_index('ix_portal_sessions_token_hash', 'portal_sessions', ['token_hash'], unique=False)
    op.create_unique_constraint('uq_portal_sessions_token_hash', 'portal_sessions', ['token_hash'])
    op.drop_index(op.f('ix_credit_issuances_issuance_uuid'), table_name='credit_issuances')
    op.create_index('ix_credit_issuances_issuance_uuid', 'credit_issuances', ['issuance_uuid'], unique=False)
    op.create_unique_constraint('credit_issuances_issuance_uuid_key', 'credit_issuances', ['issuance_uuid'])
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_index(op.f('ix_batch_stage_events_batch_uuid'), table_name='batch_stage_events')
    op.create_index('ix_stage_events_batch_uuid', 'batch_stage_events', ['batch_uuid'], unique=False)
    op.drop_index(op.f('ix_burn_sessions_batch_uuid'), table_name='burn_sessions')
    op.drop_table('burn_sessions')
    # ### end Alembic commands ###
