"""m2_9_sessions_and_courier_auth

Revision ID: 74b54f6dc74e
Revises: d1e2f3a4b5c6
Create Date: 2026-07-27 13:19:12.645756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b54f6dc74e'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # M2.9 (ADR-002 Addendum A) ONLY. The autogenerated collateral DDL that
    # originally sat here (batches FK, credit_issuances / portal_sessions /
    # portal_users constraint churn, stage-events index rename) was REMOVED:
    # it was pre-existing model/schema drift, unrelated to this feature, and
    # unsafe against live data. If that drift is worth reconciling it gets its
    # own reviewed migration.
    op.create_table(
        "burn_sessions",
        sa.Column("session_uuid", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("batch_uuid", sa.String(length=36), nullable=True),
        sa.Column("binding_source", sa.String(length=32), nullable=True),
        sa.Column("bound_by", sa.String(length=255), nullable=True),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("session_uuid"),
    )
    op.create_index(
        op.f("ix_burn_sessions_batch_uuid"), "burn_sessions", ["batch_uuid"]
    )
    op.add_column(
        "telemetry_chunks", sa.Column("session_uuid", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "telemetry_chunks",
        sa.Column("courier_device_id", sa.String(length=255), nullable=True),
    )
    op.add_column("telemetry_chunks", sa.Column("seq", sa.Integer(), nullable=True))
    op.add_column(
        "telemetry_chunks", sa.Column("prev_hash", sa.String(length=64), nullable=True)
    )
    with op.batch_alter_table("telemetry_chunks") as batch_op:
        batch_op.alter_column(
            "batch_uuid",
            existing_type=sa.VARCHAR(length=36),
            nullable=True,
        )
    op.create_index(
        op.f("ix_telemetry_chunks_session_uuid"), "telemetry_chunks", ["session_uuid"]
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_telemetry_chunks_session_uuid"), table_name="telemetry_chunks")
    with op.batch_alter_table("telemetry_chunks") as batch_op:
        batch_op.alter_column(
            "batch_uuid",
            existing_type=sa.VARCHAR(length=36),
            nullable=False,
        )
    op.drop_column("telemetry_chunks", "prev_hash")
    op.drop_column("telemetry_chunks", "seq")
    op.drop_column("telemetry_chunks", "courier_device_id")
    op.drop_column("telemetry_chunks", "session_uuid")
    op.drop_index(op.f("ix_burn_sessions_batch_uuid"), table_name="burn_sessions")
    op.drop_table("burn_sessions")
