"""Add Farmer Models

Revision ID: 840b80dc3102
Revises: 9166634b188b
Create Date: 2026-07-22 03:23:16.356971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840b80dc3102'
down_revision: Union[str, None] = '9166634b188b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farmer_uuid', sa.String(length=36), nullable=False),
    sa.Column('fpic_template_id', sa.String(length=128), nullable=True),
    sa.Column('signed_pdf_media_id', sa.String(length=64), nullable=True),
    sa.Column('holding_photo_media_id', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exclusivity_ack', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_consents_farmer_uuid'), 'farmer_consents', ['farmer_uuid'], unique=False)
    op.create_table('farmer_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farmer_uuid', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint("doc_type IN ('aadhaar', 'pan', 'passport', 'nid')", name='ck_farmer_doc_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_documents_farmer_uuid'), 'farmer_documents', ['farmer_uuid'], unique=False)
    op.create_table('farmer_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farmer_uuid', sa.String(length=36), nullable=False),
    sa.Column('rail', sa.String(length=32), nullable=False),
    sa.Column('account_holder', sa.String(length=255), nullable=True),
    sa.Column('masked_account', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=32), nullable=True),
    sa.Column('masked_upi_id', sa.String(length=255), nullable=True),
    sa.Column('masked_mfs_id', sa.String(length=255), nullable=True),
    sa.CheckConstraint("rail IN ('bank', 'upi', 'mfs')", name='ck_farmer_payment_rail'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_payments_farmer_uuid'), 'farmer_payments', ['farmer_uuid'], unique=False)
    op.create_table('farmers',
    sa.Column('farmer_uuid', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mobile_number', sa.String(length=32), nullable=False),
    sa.Column('education', sa.String(length=128), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('reported_area', sa.Float(), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('kyc_status', sa.String(length=32), nullable=True),
    sa.Column('consent_status', sa.String(length=32), nullable=True),
    sa.Column('signature_media_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('farmer_uuid'),
    sa.UniqueConstraint('project_id', 'mobile_number', name='uq_farmer_project_mobile')
    )
    op.create_index(op.f('ix_farmers_project_id'), 'farmers', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_farmers_project_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_farmer_payments_farmer_uuid'), table_name='farmer_payments')
    op.drop_table('farmer_payments')
    op.drop_index(op.f('ix_farmer_documents_farmer_uuid'), table_name='farmer_documents')
    op.drop_table('farmer_documents')
    op.drop_index(op.f('ix_farmer_consents_farmer_uuid'), table_name='farmer_consents')
    op.drop_table('farmer_consents')
    # ### end Alembic commands ###
