"""baseline

Revision ID: 8fd65cb412f6
Revises: 
Create Date: 2026-06-30 02:51:56.399498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd65cb412f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_uuid', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('feedstock_species', sa.String(length=255), nullable=False),
    sa.Column('harvest_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moisture_percent', sa.Float(), nullable=False),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('harvest_uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('sourcing_uuid', sa.String(length=36), nullable=True),
    sa.Column('moisture_compliant', sa.Boolean(), nullable=True),
    sa.Column('mock_location_enabled', sa.Boolean(), nullable=True),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('roll', sa.Float(), nullable=True),
    sa.Column('wet_yield_kg', sa.Float(), nullable=False),
    sa.Column('min_recorded_temp_c', sa.Float(), nullable=False),
    sa.Column('transport_distance_km', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('net_credit_t_co2e', sa.Float(), nullable=False),
    sa.Column('lca_methodology_version', sa.String(length=255), nullable=True),
    sa.Column('lca_audit_json', sa.Text(), nullable=True),
    sa.Column('lca_signature', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_uuid'), 'batches', ['batch_uuid'], unique=True)
    op.create_index(op.f('ix_batches_device_id'), 'batches', ['device_id'], unique=False)
    op.create_index(op.f('ix_batches_operation_id'), 'batches', ['operation_id'], unique=True)
    op.create_table('device_keys',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('hmac_key', sa.String(length=64), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('end_use_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_uuid', sa.String(length=36), nullable=False),
    sa.Column('batch_uuid', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_end_use_application_application_uuid'), 'end_use_application', ['application_uuid'], unique=True)
    op.create_index(op.f('ix_end_use_application_batch_uuid'), 'end_use_application', ['batch_uuid'], unique=True)
    op.create_table('enrollment_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('pyrolysis_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telemetry_uuid', sa.String(length=36), nullable=False),
    sa.Column('batch_uuid', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pyrolysis_telemetry_batch_uuid'), 'pyrolysis_telemetry', ['batch_uuid'], unique=True)
    op.create_index(op.f('ix_pyrolysis_telemetry_telemetry_uuid'), 'pyrolysis_telemetry', ['telemetry_uuid'], unique=True)
    op.create_table('system_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_uuid', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metadata_batch_uuid'), 'system_metadata', ['batch_uuid'], unique=True)
    op.create_table('yield_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('yield_uuid', sa.String(length=36), nullable=False),
    sa.Column('batch_uuid', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yield_metrics_batch_uuid'), 'yield_metrics', ['batch_uuid'], unique=True)
    op.create_index(op.f('ix_yield_metrics_yield_uuid'), 'yield_metrics', ['yield_uuid'], unique=True)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_uuid', sa.UUID(), nullable=True),
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_uuid'], ['batches.batch_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_operation_id'), 'media_files', ['operation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_files_operation_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_yield_metrics_yield_uuid'), table_name='yield_metrics')
    op.drop_index(op.f('ix_yield_metrics_batch_uuid'), table_name='yield_metrics')
    op.drop_table('yield_metrics')
    op.drop_index(op.f('ix_system_metadata_batch_uuid'), table_name='system_metadata')
    op.drop_table('system_metadata')
    op.drop_index(op.f('ix_pyrolysis_telemetry_telemetry_uuid'), table_name='pyrolysis_telemetry')
    op.drop_index(op.f('ix_pyrolysis_telemetry_batch_uuid'), table_name='pyrolysis_telemetry')
    op.drop_table('pyrolysis_telemetry')
    op.drop_table('enrollment_tokens')
    op.drop_index(op.f('ix_end_use_application_batch_uuid'), table_name='end_use_application')
    op.drop_index(op.f('ix_end_use_application_application_uuid'), table_name='end_use_application')
    op.drop_table('end_use_application')
    op.drop_table('device_keys')
    op.drop_index(op.f('ix_batches_operation_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_device_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_uuid'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
